<?php

namespace ContainerPQjjbxH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XBOsIyWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XBOsIyW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XBOsIyW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\BlogController::index' => ['privates', '.service_locator.17N9eJL.App\\Controller\\BlogController::index()', 'getBlogControllerindexService', true],
            'App\\Controller\\BlogController::add' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\BlogController::add()', 'getBlogControlleraddService', true],
            'App\\Controller\\BlogController::show' => ['privates', '.service_locator.Z.3asT3.App\\Controller\\BlogController::show()', 'getBlogControllershowService', true],
            'App\\Controller\\BlogController::edit' => ['privates', '.service_locator.pKtYbk8.App\\Controller\\BlogController::edit()', 'getBlogControllereditService', true],
            'App\\Controller\\BlogController::delete' => ['privates', '.service_locator.Z.3asT3.App\\Controller\\BlogController::delete()', 'getBlogControllerdeleteService', true],
            'App\\Controller\\LoginController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\LoginController::login()', 'getLoginControllerloginService', true],
            'App\\Controller\\PostController::deleteComment' => ['privates', '.service_locator.aCnRYOo.App\\Controller\\PostController::deleteComment()', 'getPostControllerdeleteCommentService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\BlogController:index' => ['privates', '.service_locator.17N9eJL.App\\Controller\\BlogController::index()', 'getBlogControllerindexService', true],
            'App\\Controller\\BlogController:add' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\BlogController::add()', 'getBlogControlleraddService', true],
            'App\\Controller\\BlogController:show' => ['privates', '.service_locator.Z.3asT3.App\\Controller\\BlogController::show()', 'getBlogControllershowService', true],
            'App\\Controller\\BlogController:edit' => ['privates', '.service_locator.pKtYbk8.App\\Controller\\BlogController::edit()', 'getBlogControllereditService', true],
            'App\\Controller\\BlogController:delete' => ['privates', '.service_locator.Z.3asT3.App\\Controller\\BlogController::delete()', 'getBlogControllerdeleteService', true],
            'App\\Controller\\LoginController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\LoginController::login()', 'getLoginControllerloginService', true],
            'App\\Controller\\PostController:deleteComment' => ['privates', '.service_locator.aCnRYOo.App\\Controller\\PostController::deleteComment()', 'getPostControllerdeleteCommentService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\BlogController::index' => '?',
            'App\\Controller\\BlogController::add' => '?',
            'App\\Controller\\BlogController::show' => '?',
            'App\\Controller\\BlogController::edit' => '?',
            'App\\Controller\\BlogController::delete' => '?',
            'App\\Controller\\LoginController::login' => '?',
            'App\\Controller\\PostController::deleteComment' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\BlogController:index' => '?',
            'App\\Controller\\BlogController:add' => '?',
            'App\\Controller\\BlogController:show' => '?',
            'App\\Controller\\BlogController:edit' => '?',
            'App\\Controller\\BlogController:delete' => '?',
            'App\\Controller\\LoginController:login' => '?',
            'App\\Controller\\PostController:deleteComment' => '?',
        ]);
    }
}
