<?php

namespace ContainerPQjjbxH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pKtYbk8.App\Controller\BlogController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pKtYbk8.App\\Controller\\BlogController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'blogPost' => ['privates', '.errored..service_locator.pKtYbk8.App\\Entity\\BlogPost', NULL, 'Cannot autowire service ".service_locator.pKtYbk8": it needs an instance of "App\\Entity\\BlogPost" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'blogPost' => 'App\\Entity\\BlogPost',
            'em' => '?',
        ]))->withContext('App\\Controller\\BlogController::edit()', $container);
    }
}
