<?php

namespace ContainerMxAqsax;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Z.3asT3.App\Controller\BlogController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.Z.3asT3'] ?? $container->load('get_ServiceLocator_Z_3asT3Service'));

        if (isset($container->privates['.service_locator.Z.3asT3.App\\Controller\\BlogController::show()'])) {
            return $container->privates['.service_locator.Z.3asT3.App\\Controller\\BlogController::show()'];
        }

        return $container->privates['.service_locator.Z.3asT3.App\\Controller\\BlogController::show()'] = $a->withContext('App\\Controller\\BlogController::show()', $container);
    }
}
