<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPQjjbxH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPQjjbxH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPQjjbxH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPQjjbxH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPQjjbxH\App_KernelDevDebugContainer([
    'container.build_hash' => 'PQjjbxH',
    'container.build_id' => '4eee5839',
    'container.build_time' => 1739540632,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPQjjbxH');
